name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      #- name: Lint
      #  uses: j2kun/chktex-action@v2
      #  with:
      #    lint-all: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: ./src/book/main
          latexmk_use_lualatex: true
          root_file: scroll.tex
          pre_compile: |
            mkdir -p /etc/fonts/conf.d
            cp /usr/local/texlive/2026/texmf-var/fonts/conf/texlive-fontconfig.conf /etc/fonts/conf.d/09-texlive.conf
            fc-cache -fsv
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode --shell-escape
        env:
          TEXINPUTS: ".:./src/book/main//:"
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: scroll.pdf
